// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhovxtnavxbuonhnmwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaG92eHRuYXZ4YnVvbmhubXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDQ0ODgsImV4cCI6MjA2MTg4MDQ4OH0.TUfJeaMTWE6Vq6kYifa3j2Lfgj7-7fCaphsP2TwvpEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);